### ISSUE TITLE
Option to open videos in a custom web view window to override CSS

### ISSUE THREAD

**Issue by agentcooper** [agentcooper/Telik#5]
A new option should be added to Open videos select in Preferences.

The goal is to allow blocking various distractions like related videos when the video is paused or finished.

It can be achieved with a custom web view window with some injected CSS. An option to modify that CSS should be added to Preferences as well.

<img width="1064" alt="Screenshot 2022-06-21 at 13 48 00" src="https://user-images.githubusercontent.com/794591/174792538-92185723-7c26-4f57-8d4e-38b705935f1e.png">

<img width="1064" alt="Screenshot 2022-06-21 at 13 49 54" src="https://user-images.githubusercontent.com/794591/174792548-d4f522e8-e3dc-4c47-b0ae-e7d631bdea1a.png">

These can be blocked with:
```css
.ytp-pause-overlay {
  display: none !important;
}

.videowall-endscreen {
  display: none !important;
}
```
